"""Added users and roles

Revision ID: d1d0c43a1e27
Revises: add_warehouse_id
Create Date: 2026-03-25 15:17:27.250933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1d0c43a1e27'
down_revision = 'add_warehouse_id'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.alter_column('conversion_batches', 'warehouse_id',
               existing_type=sa.INTEGER(),
               server_default='1',
               existing_nullable=False)
    op.alter_column('conversions', 'warehouse_id',
               existing_type=sa.INTEGER(),
               server_default='1',
               existing_nullable=False)
    op.alter_column('order_tracker', 'warehouse_id',
               existing_type=sa.INTEGER(),
               server_default='1',
               existing_nullable=False)
    op.alter_column('orders', 'warehouse_id',
               existing_type=sa.INTEGER(),
               server_default='1',
               existing_nullable=False)
    op.alter_column('transactions', 'warehouse_id',
               existing_type=sa.INTEGER(),
               server_default='1',
               existing_nullable=False)
    op.alter_column('warehouses', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('warehouses', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('transactions', 'warehouse_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('orders', 'warehouse_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('order_tracker', 'warehouse_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversions', 'warehouse_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversion_batches', 'warehouse_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_table('users')
    # ### end Alembic commands ###
